# Generated by Django 4.2 on 2023-06-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="name",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
