# Generated by Django 4.2 on 2023-06-27 18:18

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("test1", "0002_post_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="posdtheader",
            new_name="posdcontext",
        ),
        migrations.RemoveField(
            model_name="post",
            name="name",
        ),
        migrations.AddField(
            model_name="post",
            name="createdat",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="posttitle",
            field=models.TextField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="urlimg",
            field=models.URLField(
                default=datetime.datetime(
                    2023, 6, 27, 18, 18, 9, 762683, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
