# Generated by Django 4.2 on 2023-06-27 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test1", "0003_rename_posdtheader_post_posdcontext_remove_post_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="catalogue",
            field=models.TextField(
                default=datetime.datetime(
                    2023, 6, 27, 18, 41, 49, 489562, tzinfo=datetime.timezone.utc
                ),
                max_length=40,
            ),
            preserve_default=False,
        ),
    ]
