# Generated by Django 4.2 on 2023-07-03 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test1", "0004_post_catalogue"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="posdcontext",
            new_name="description",
        ),
        migrations.AddField(
            model_name="post",
            name="postcontext",
            field=models.TextField(
                default=datetime.datetime(
                    2023, 7, 3, 14, 2, 37, 315903, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="posturl",
            field=models.URLField(
                default=datetime.datetime(
                    2023, 7, 3, 14, 2, 46, 647893, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
