# Generated by Django 4.2 on 2023-07-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test1", "0005_rename_posdcontext_post_description_post_postcontext_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="createdat",
            field=models.TextField(),
        ),
    ]
